//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadlineVisualizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeadlineVisualizer.Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar weeks.
        /// </summary>
        internal static string CalendarWeeksString {
            get {
                return ResourceManager.GetString("CalendarWeeksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string DaysString {
            get {
                return ResourceManager.GetString("DaysString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default calendar unit.
        /// </summary>
        internal static string DefaultCalendarUnit {
            get {
                return ResourceManager.GetString("DefaultCalendarUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning levels should be descending.
        /// </summary>
        internal static string SettingsErrorMessage {
            get {
                return ResourceManager.GetString("SettingsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsSaveButtonText {
            get {
                return ResourceManager.GetString("SettingsSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string SettingsSaveSuccessful {
            get {
                return ResourceManager.GetString("SettingsSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Level 1 (days).
        /// </summary>
        internal static string WarningLevel1DistanceText {
            get {
                return ResourceManager.GetString("WarningLevel1DistanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Level 2 (days).
        /// </summary>
        internal static string WarningLevel2DistanceText {
            get {
                return ResourceManager.GetString("WarningLevel2DistanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Level 3 (days).
        /// </summary>
        internal static string WarningLevel3DistanceText {
            get {
                return ResourceManager.GetString("WarningLevel3DistanceText", resourceCulture);
            }
        }
    }
}
